version: "3"

services:
  db:
    user: 1000:1000
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=test_db
    volumes:
      - dj_postgres_data:/var/lib/postgresql/data/
  django:
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - ./inventoryproject/.env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./assets/nginx/nginx.http.config:/etc/nginx/nginx.conf
      #- ./assets/nginx/certs:/etc/nginx/certs
      - static_volume:/app/static
    ports:
      # - "443:443"
      - "80:80"
    depends_on:
      - django

volumes:
  dj_postgres_data:
  static_volume: