# Generated by Django 3.2.8 on 2021-10-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Pc', 'Pc'), ('Keyboard', 'Keyboard'), ('Phone', 'Phone'), ('Mouse', 'Mouse'), ('Speaker', 'Speaker'), ('Monitor', 'Monitor'), ('IT Equipment', 'IT Equipment')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
