# Generated by Django 3.2.8 on 2021-10-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagement', '0002_auto_20211018_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
