# Generated by Django 3.2.8 on 2021-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagement', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Pc', 'Pc'), ('Keyboard', 'Keyboard'), ('Phone', 'Phone'), ('Mouse', 'Mouse'), ('Speaker', 'Speaker'), ('Monitor', 'Monitor'), ('IT Equipment', 'IT Equipment')], max_length=50, null=True),
        ),
    ]
