# Generated by Django 3.2.8 on 2021-10-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagement', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
