# Generated by Django 3.2.8 on 2021-10-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagement', '0004_auto_20211019_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invmanagement.category'),
            preserve_default=False,
        ),
    ]
