# Generated by Django 3.2.8 on 2021-10-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagement', '0007_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
