# Generated by Django 3.2.8 on 2021-10-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invmanagement', '0008_remove_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price',
        ),
    ]
