# Generated by Django 3.2.8 on 2021-11-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pc', 'Pc'), ('Keyboard', 'Keyboard'), ('Phone', 'Phone'), ('Mouse', 'Mouse'), ('Speaker', 'Speaker'), ('Monitor', 'Monitor'), ('IT Equipment', 'IT Equipment')], max_length=50)),
                ('prod_name', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(default='0', null=True)),
                ('availability', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
